### ISSUE TITLE
Please include 'Mixture Content Selection for Diverse Sequence Generation (EMNLP 2019)'

### ISSUE THREAD

**Issue by j-min** [teacherpeterpan/Question-Generation-Paper-List#3]
Please include our paper [Mixture Content Selection for Diverse Sequence Generation (EMNLP 2019)](https://www.semanticscholar.org/paper/Mixture-Content-Selection-for-Diverse-Sequence-Cho-Seo/8270fcc6cb531e43d30091ac897831063826c097).
We didn't mention question generation in the title, but we evaluated our model both in question generation (SQuAD) and abstractive summarization (CNN/DM) and improved the accuracy and diversity of existing approaches.

**Comment by teacherpeterpan** [comment]
Thanks for reminding us. We have included your paper into our paper list.
