### ISSUE TITLE
Include "Asking Questions the Human Way: Scalable Question-Answer Generation from Text Corpus"

### ISSUE THREAD

**Issue by flackbash** [teacherpeterpan/Question-Generation-Paper-List#5]
The paper [Asking Questions the Human Way: Scalable Question-Answer Generation from Text Corpus](https://arxiv.org/pdf/2002.00748.pdf) by Liu et al looks very interesting and seems to be a perfect match for your list :)

And thanks a lot for making this list public!

**Comment by teacherpeterpan** [comment]
Yes, this is a good paper. I have added it to the list. Thanks for recommending this paper to us.
