### ISSUE TITLE
Asking Clarification Questions in Knowledge-Based Question Answering may be included

### ISSUE THREAD

**Issue by Desperado721** [teacherpeterpan/Question-Generation-Paper-List#6]
Hi, Liangming,

I'm Jie. I found a good paper about Clarification question generation. It may be a good match for your paperlist if you're interested. :)

https://www.aclweb.org/anthology/D19-1172.pdf

**Comment by teacherpeterpan** [comment]
Hi Jie, 

Thanks so much for your recommendation. This is a great paper. I have added it to the list.
